import './globals.css';
import { BaseUrlProvider } from './context/BaseUrlContext';

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<BaseUrlProvider>
					{children}
				</BaseUrlProvider>
			</body>
		</html>
	);
}
